name: Report Bug
description: Report a bug causing unexpected provider behaviour.
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for reporting a bug! :+1:

        Before submitting a bug report, please check for existing issues that may report the same issue to keep all relevant information in one place.

        To request new resources, data sources or services, please use the ['Request New Resource, Data Source or ATLASSIAN Service'](https://github.com/openscientia/terraform-provider-atlassian/issues/new?assignees=&labels=needs-triage&template=new_resource.yml) form.
        
        To request additional functionality for existing resources, data sources or the provider itself, please use the ['Request Enhancement'](https://github.com/openscientia/terraform-provider-atlassian/issues/new?assignees=&labels=enhancement,needs-triage&template=enhancement.yml) form.

  - type: input
    id: tf_cli_version
    attributes:
      label: Terraform CLI Version
      description: The semantic version of the Terraform CLI used when experiencing the bug. If multiple versions have been tested, a comma separated list.
      placeholder: "X.Y.Z"
    validations:
      required: true

  - type: input
    id: provider_version
    attributes:
      label: ATLASSIAN Provider Version
      description: The semantic version of the ATLASSIAN Provider used when experiencing the bug. If multiple versions have been tested, a comma separated list.
      placeholder: "X.Y.Z"
    validations:
      required: true

  - type: textarea
    id: affected-resources
    attributes: 
      label: Affected Resources
      description: Please list the affected resource(s) and/or data source(s).
      placeholder: |
        - atlassian_<service>_<resource_name>
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Description of what should have happened.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error/Panic Output Snippet
      description: |
        If relevant, provide a snippet of the error/panic output. This will be rendered with `shell` syntaxt highlighting, do not use [code fences](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
      render: Shell
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Configuration and Logging

        If appropriate, provide the Terraform configuration and, when possible, the debug logs. For configurations or logs of more than just a few lines, it's preferred to either share a Gist link or zip the files and upload them.

        Terraform configurations or debug logs under 25MB may be [attached directly in the field](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files). Files larger than this should be uploaded to a file hosting service and a link shared.

        **Note:** The form fields below do not automatically render, so you will need to use [code fence(s)](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to achieve proper formatting.

  - type: textarea
    id: tf_config
    attributes:
      label: Terraform Configuration Files
      description: |
        Please paste, upload, or link to a file or Gist containing all Terraform configurations required to reproduce the bug. See note above for additional information on file size restrictions and encrypting.

        Bug reports without a functional reproduction may be closed without investigation.
    validations:
      required: false

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: List of steps to reproduce the bug.
      placeholder: |
        1. `terraform apply`
    validations:
      required: true

  - type: textarea
    id: debug_logs
    attributes:
      label: Debug Output
      description: |
        If possible, please paste, upload, or link to a file or Gist containing debug logs. See note above for additional information on file size restrictions and encrypting.

        To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).
    validations:
      required: false

  - type: textarea
    id: panic_logs
    attributes:
      label: Panic Output
      description: If Terraform produced a panic, please paste, upload, or link to a file or Gist containing the output of the `crash.log`.
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: references
      description: |
        Additional details such as links to any other relevant documentation, other GitHub issues and/or pull requests.

        [How to reference Github Issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls)
    validations:
      required: false
