name: Documentation Issue
description: Report an issue in the provider documentation or contribution guide.
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for reporting a documentation issue! :+1:

        Please use this form to alert the maintainers about documentation issues in the [Terraform Registry](https://registry.terraform.io/providers/openscientia/atlassian/latest/docs) or the [contribution guide]().

        To request new resources, data sources or services, please use the ['Request New Resource, Data Source or ATLASSIAN Service'](https://github.com/openscientia/terraform-provider-atlassian/issues/new?assignees=&labels=needs-triage&template=new_resource.yml) form.
        
        To request additional functionality for existing resources, data sources or the provider itself, please use the ['Request Enhancement'](https://github.com/openscientia/terraform-provider-atlassian/issues/new?assignees=&labels=enhancement,needs-triage&template=enhancement.yml) form.

        To report unexpected provider behaviour, please use the ['Report Bug'](https://github.com/openscientia/terraform-provider-atlassian/issues/new?assignees=&labels=bug&template=bug.yml) form.

  - type: textarea
    id: tf_registry_link
    attributes:
      label: Documentation Link
      description: Link to the afected page on the Terraform Registry documentation or contribution guide.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the documentation issue.
    validations:
      required: true
      
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Additional details such as links to any other relevant documentation, other GitHub issues and/or pull requests.

        [How to reference Github Issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls)
    validations:
      required: false
