name: Request Enhancement
description: Request an enhancement for a resource, data source or 
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for submitting an enhancement request! :+1:

        Please use this form to request additional functionality for existing resources, data sources, or the provider itself.

        To report unexpected provider behaviour, please use the ['Report Bug'](https://github.com/openscientia/terraform-provider-atlassian/issues/new?assignees=&labels=bug&template=bug.yml) form.

        To request new resources, data sources or services, please use the ['Request New Resource, Data Source or ATLASSIAN Service'](https://github.com/openscientia/terraform-provider-atlassian/issues/new?assignees=&labels=needs-triage&template=new_resource.yml) form.
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the requested enhancement.
    validations:
      required: true

  - type: textarea
    id: affected-resources
    attributes:
      label: Affected Resource(s) and/or Data Source(s)
      description: Please list the affected resource(s) and/or data source(s).
      placeholder: |
        - atlassian_<service>_<resource_name>
    validations:
      required: false

  - type: textarea
    id: proposal
    attributes:
      label: Potential Terraform Configuration
      description: | 
        What would the Terraform HCL syntax look like for the new resource(s) and/or data source(s)?. This will be rendered with `terraform` syntax highlighting by default, do not use [code fences](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
      render: terraform
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: references
      description: |
        Additional details such as links to any other relevant documentation, other GitHub issues and/or pull requests.

        [How to reference Github Issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls)
    validations:
      required: false
