name: Workflow Linting
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/*
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Install actionlint
        run: cd tools && go install github.com/rhysd/actionlint/cmd/actionlint
      - name: Run actionlint on workflow files
        run: actionlint -shellcheck= -ignore '(download-path)'